### ISSUE TITLE
Documentation suboptimal

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#118]
The handbook has more docs on this extension than the extension itself: http://handbook.datalad.org/en/latest/basics/101-133-containersrun.html

The frontpage links to http://docs.datalad.org/projects/container/en/latest/ which doesn't even have API docs rendered.

**Comment by yarikoptic** [comment]
> The handbook has more docs on this extension than the extension itself: http://handbook.datalad.org/en/latest/basics/101-133-containersrun.html

isn't it a general state of things in the datalad ecosystem, that handbook is more comprehensive?


> doesn't even have API docs rendered.

yeah, strange -- something bugs out I guess since it seems that the docstring is there:
```python
@build_doc
# all commands must be derived from Interface
class ContainersAdd(Interface):
    # first docstring line is used a short description in the cmdline help
    # the rest is put in the verbose help and manpage
    """Add a container to a dataset
    """
```

> The frontpage links to http://docs.datalad.org/projects/container/en/latest/

I think we should add handbook into intersphinx and then reference that http://handbook.datalad.org/en/latest/basics/101-133-containersrun.html and also point to it in README.md . Otherwise I think that the documentation of this extension should be really extensive.

**Comment by adswa** [comment]
BTW, the docs have been failing to build for 11 months. The [logs](https://readthedocs.org/projects/datalad-container/builds/12228694/) suggest that the primary reason for this is that they are build in a Python 2 environment.
I believe that this is easy to fix, someone with admin privileges should try to go to https://readthedocs.org/dashboard/datalad-container/advanced/ and switch the Python intepreter from CPython2.x to CPython3.x

**Comment by mih** [comment]
I am closing this issue of mine before it would have to be enrolled in school. #223 provides the minimal link to largest body of documentation that we have.
