### ISSUE TITLE
Link containers provided by subdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#33]
It is beneficial to be able to maintain "toolchain" datasets that provide a range of containers (of the right versions). With those it is sufficient to link to one of such datasets as a subdataset to provide a wide range of functionality, instead of duplicating container configuration effort over and over.

There is an issue however: How to do this, such that:
- no (or very little) duplicate configuration settings are created that all have the potential to get outdated (image moved, URL changed, ...)
- functionality is not impaired wrt to a straight inclusion of a container image into a dataset

### Proposal

- `containers-add` gets enhanced with the ability to add a toolchain subdataset
- for each container in a toolchain dataset, the parent dataset gets the variable `datalad.container.<name>.providedby = <subdataset path>` set.
  - This will make sure that there are no future namespace conflicts within the scope of the parent dataset
  - It will make `list` work (needs ability to mark individual containers as known, but absent when subdataset is not installed)
  - It will make `remove` work (the variable get's removed and subsequently the container is unknown to the parent, independent of the subdataset state)
  - It minimizes the linkage (and potential for breakage) between parent dataset and subdataset configuration

Pretty much all container commands would need to be adjusted to resolve container properties from the identified subdataset, but that should be a minor effort.

I do not foresee problems regarding a future `containers-update` command. It could simply `update --merge` any toolchain subdataset known, and update the config.

**Comment by yarikoptic** [comment]
- what about supplementing with `datalad.containers.providedby = <subdataset path>`, allowing for multiple values thus establishing the order in case of multiple datasets.  So if there is no `datalad.container.<name>.providedby` -- could just look up in the subdatasets?  otherwise, with necessity to configure for each one of the commands -- tedious would get out of sync etc
- ideally (farfetching) I see a point of `install` (or `clone`) acquiring some option which would instruct about the nature of the subdataset, so if I did something like `datalad install -d . --track=containers http://url/containers`, the needed config entry would get added automagically.  It is to a degree similar to `git` operation -- many commands establish "Default" (or requested, as `push --set-upstream`) configuration within `.git/config` -- tracking of remotes, what to push, etc.  If we had to modify .git/config for everything - it would be too tedious and too painful.

**Comment by yarikoptic** [comment]
Another aspect - probably .gitmodules is the best place to record any information which is subdataset specific - eg if to be the one providing container names etc... This way removal (or moving/renaming) of subdataset would automagically remove (move) all associated information

**Comment by mih** [comment]
Very good point!

**Comment by bpoldrack** [comment]
#51 follows a different at much simpler approach. Simply let `containers-list` report registered containers recursively. This is done by returning a name prefixed with the subdataset's name (and a slash), separating name spaces per dataset. Since the result reports everything needed for `containers-run` there's no need to distinguish between config of a container within a dataset and a subdataset.
Therefore, adding some toolbox simply is adding a subdataset, that has registered containers.

I think the only thing to discuss is whether or not `containers-add` and `remove` should be able to adress containers within a subdataset when `run` is. I'm fine with their inability to do so, but may be they should recognize a container's name as not belonging to their accessible name space and provide a telling message.
What do you guys think, @datalad/developers ?
