### ISSUE TITLE
container exec vs run  and our defaults - should we support configuration for both modes?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#61]
ATM we rely on `singularity exec` as being the default way to interact with the container.  It makes sense in particular to align `datalad run` and `datalad containers-run` invocation so the `{cmd}` is present in both.  BUT
- many (if not the majority) containers are prepared to have their target application run upon `run`. So it makes sense to "run" those containers instead of "exec" and manually providing the `{cmd}`
- there might be an entry point script which adjusts environment for making it possible to use target application.  E.g. `neurodocker` generated containers for FSL would do `source /etc/fsl/fsl.sh` for us, and without going through the `run` container environment would not be fully prepared.

Since it is a common for both singularity and docker, I wonder if we should add an option to `containers-add` to specify the type of invocation (`run` vs `exec`) which would then provide appropriate default config within `.datalad/config` depending on that specification. That would mean though, that for those containers which are `run`'ed, there might (or might not) be `{cmd}` specified on cmdline.  E.g. for reproin ATM [we specify](https://github.com/ReproNim/reproin/blob/master/generate_container.sh) `--entrypoint "/neurodocker/heudiconv.sh"` so we could still `run` the container but with the `{cmd}` and so that environment is fully prepared by that script

**Comment by kyleam** [comment]
Related to #46.

**Comment by mih** [comment]
Given that this issues has not seen any attention in the past four years, I'd say that the demand for this feature is low. Moreover, it is mostly a convenience, because it is possible to call the `run` entrypoint, by setting a configuration similar to the following:

```
[datalad "containers.cat"]
        image = .datalad/environments/cat/image
        cmdexec = singularity run -B {{pwd}} --cleanenv {img} {cmd}
```

(from a randomly picked real-world application)

This can be set via the `datalad containers-add --call-fmt` option.

In general, particular images and applications tend to have relatively complex requirements re singularity setup pretty quickly (think bind-mounts, environment sanitization, etc.). Supporting these individually would mean to run after the development of all supported container technologies, or to run into future conflicts across these technologies. I would personally prefer to stick with `--call-fmt` that enables all of them, discriminates against none, albeit not being the most convenient in some simple cases).
